services:
  api_poller:
    build: api_poller
    depends_on:
      - rabbitmq
    volumes:
      - ./api_poller:/usr/src/app
    env_file:
      - api_poller.env
      - common.env

  rabbitmq:
    image: rabbitmq